# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_voivodeship_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='voivodeship',
            name='no',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('candidate', 'circuit')]),
        ),
    ]
