# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20170330_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondname',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='surname',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
